apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yo3wyzfda-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yo3wyzfda-go 
  name: yo3wyzfda-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yo3wyzfda-go 
