apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yo3wyzfda-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:489c3696eecb3d8b92898e2ad9c194141a8f3ff8@sha256:c391c1934806f6761743aafb3ff919fca72dbb698116f5b238f24ec3b4dfb661
          name: container-image
